import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Footer from '@/ui/footers/footer'
import { Header } from '@/ui'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;700&family=Montserrat+Alternates:wght@400;700&family=Urbanist:wght@400;700&family=DM+Serif+Display&display=swap" rel="stylesheet" />
                <link rel='stylesheet' href='/assets/css/flaticon.css' />
                <link rel="stylesheet" href='/assets/css/font-awesome-pro.css' />
            </head>
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
