import type { Metadata } from 'next'
import './globals.css'
import Footer from '@/ui/footers/footer'
import { AnimateMouse, Header } from '@/ui'
import { AppProvider } from '@/context'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' style={{ scrollBehavior: 'smooth' }}>
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
                <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap" rel="stylesheet"></link>
                <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&display=swap" rel="stylesheet"></link>
                <link href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>
                <link rel='stylesheet' href='/assets/css/flaticon.css' />
                <link rel="stylesheet" href='/assets/css/font-awesome-pro.css' />
            </head>
            <body>
                <AppProvider>
                    <AnimateMouse />
                    <Header />
                    {children}
                    <Footer />
                </AppProvider>
            </body>
        </html>
    )
}
